### ISSUE TITLE
Collaboration going forward

### ISSUE THREAD

**Issue by rodneyrehm** [medialize/tokenlist#1]
Hey @bkardell @jwilsson,

I've created a new implementation of the DOMTokenList interface based on both your works. I did this because neither project fulfilled all of my requirements (modularized, extensible, fully tested).

The question is if and how we're able to merge our efforts on [jwilsson/domtokenlist](https://github.com/jwilsson/domtokenlist) and [bkardell/tokenListFor](https://github.com/bkardell/tokenListFor) and this repository, to minimize our individual efforts going forward.
- This project isn't quite finished, as a build job for a minified distributable is still missing. 
- This thing doesn't have to stay in my name and it doesn't have to be called "TokenList.js".
- Everything here is a suggestion. 

Until we're clear on how to proceed, this repository remains private. However this plays out, I will publish this project eventually, because I intend to use it in [ally.js](http://allyjs.io).

:)

**Comment by rodneyrehm** [comment]
Here are a few numbers comparing DOMTokenList and TokenList:
- TokenList comes in at 4.3K minified (1.7K gzipped)
- DOMTokenList is about half the size of TokenList (no UMD modules, missing iterator, no replace())
- DOMTokenList is about 4x faster at parsing (does not remove duplicates) 
- DOMTokenList is about 8x faster at mutating (does not support "live collections" and therefore skips the parsing step)

TokenList does _not_ support "array access" (`.classList[2]`, defined by `getter DOMString? item(unsigned long index);`), which DOMTokenList currently provides in a writable fashion.

**Comment by rodneyrehm** [comment]
I've found a hack for the getter (eaa5cc8) and added a build tool. I can't say I'm extremely happy with how this turned out (given the increased file size and performance penalty), but that's what it is…

**Comment by bkardell** [comment]
So, I'm just looking at this now - I'm slightly confused.... there is no equivalent of a simple tokenListFor(prop)?

**Comment by rodneyrehm** [comment]
It's in a branch I haven't merged yet. The application of this implementation to satisfy your proposal is unspectacular, [see here](https://github.com/rodneyrehm/tokenlist/blob/tokenlist-for/src/_tokenListFor.js#L23-L30).

**Comment by bkardell** [comment]
I see... do you plan to merge it?  what's the point of leaving it unmerged?

**Comment by rodneyrehm** [comment]
> do you plan to merge it? what's the point of leaving it unmerged?

I wasn't sure if we should provide that prollyfill alongside the DOMTokenList implementation and the polyfills. If you solely use the `_tokenListFor()` approach, there's no need for the polyfills… How would you like this handled?

**Comment by bkardell** [comment]
Well, I thought the purpose was really to unify them so it was one thing.  Especially if it is like 10 lines or less, I'd just pack it up.

**Comment by rodneyrehm** [comment]
ok, I'll try to do that tomorrow. What's @jwilsson's take on any of this?

**Comment by rodneyrehm** [comment]
I've been asking myself why this whole [fixing sub-standard behavior](https://github.com/rodneyrehm/tokenlist/blob/238a868/src/polyfill.js#L90-L145) business is done in all of the available polyfills, rather than simply overwriting `Element#classList` to return the custom implementation of DOMTokenList and be done with it.

In browsers that support `.classList` but don't support `.relList`, you'll get different implementations. The same is true where `SVGElement#classList` isn't supported. (This of course won't matter to you if you're only interested in `.classList`…)

At this point I'm thinking to replace the polyfill by a variation that simply overwrites `.classList` and `.relList` on `Element`, `HTMLElement` and `SVGElement` if the don't exist or lack functionality. objections?

**Comment by bkardell** [comment]
hmm... unsure.  I can see arguments both ways.  This is exactly why I propose that we treat new features prollyfills that way until we are truly sure/compatible though.  one thing for sure, the prollyfilled functionality for `_tokenListFor(prop)` should provide a universal, consistent implementation regardless of the browser.

**Comment by rodneyrehm** [comment]
The alternative would be to drop the polyfill completely as I don't need it myself. ally.js - for which I'm doing all of this in the first place - would do fine with `_tokenListFor('class')`.

I'm still waiting for @jwilsson to voice his opinion. If he's not on board, I'm happy to drop the polyfill and roll with only the prollyfill.

**Comment by jwilsson** [comment]
I don't have a strong opinion on one way or the other actually. But I agree that it's better to just provide a prollyfill instead of trying to "fix" various differences in browser behavior.

**Comment by rodneyrehm** [comment]
Thanks Jonathan! In this case I'll remove the polyfill. @bkardell, do you want to take the code and tests over to your repository, or should I publish it? After the polyfill is removed the only addition to what you have right now is the `_referenceListFor()`, usable on things like `aria-labelledby`.

**Comment by bkardell** [comment]
feel free to publish it yourself.  if you want to send a pull or something instead to retain existing links, that's fine too.  I'm more concerned that we get use/feedback/progress than maintaining control of it or something.  If you take it, some kind of link/ack would be nice, but again, not required.

**Comment by rodneyrehm** [comment]
I have removed the polyfill and converted the remainder to ES6 modules (including a bundle, AMD and CommonJS modules in `/dist`). The project is published to [npm](https://www.npmjs.com/package/tokenlist). The bundle can be loaded [via RawGit](https://cdn.rawgit.com/medialize/tokenlist/0.1.0/dist/tokenlist.min.js).
